pull_request_rules:
  - name: automatic Dependabot merge when CI passes
    conditions:
      - author~=^dependabot(|-preview)\[bot\]$
      - "status-success=ci/circleci: build"
      - base=master
    actions:
      merge:
        method: merge
  - name: delete head branch after merge
    conditions: []
    actions:
      delete_head_branch: {}
  - name: remove outdated reviews
    conditions:
      - base=master
    actions:
      dismiss_reviews: {}
