name: test
on: [push, pull_request, workflow_dispatch]

jobs:
  test-nix:
    strategy:
      matrix:
        runs-on: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.runs-on }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
      - name: Run Tests in Bash
        run: make test
        shell: bash
        env:
          TEST_SHELL: bash
          IMGUR_KEY: ${{ secrets.IMGUR_KEY }}
          OMDB_KEY: ${{ secrets.OMDB_KEY }}
          TWITTER_CLIENTID: ${{ secrets.TWITTER_CLIENTID }}
          TWITTER_CLIENTSECRET: ${{ secrets.TWITTER_CLIENTSECRET }}
