name: test and build
on: [push, pull_request, workflow_dispatch]

jobs:
  test-nix:
    strategy:
      matrix:
        runs-on: [ubuntu-latest]
    runs-on: ${{ matrix.runs-on }}
    steps:
      - uses: actions/checkout@v2
      # https://github.com/actions/setup-go
      - uses: actions/setup-go@v2
      # Cache go modules to speed up runs
      # https://github.com/actions/cache/blob/main/examples.md#go---modules
      - uses: actions/cache@v2
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - uses: actions/upload-artifact@master
        with:
          name: my-artifact
          path: build/*
      - name: Run tests
        run: make test
        env:
          TEST_SHELL: bash
          IMGUR_KEY: ${{ secrets.IMGUR_KEY }}
          OMDB_KEY: ${{ secrets.OMDB_KEY }}
          TWITTER_CLIENTID: ${{ secrets.TWITTER_CLIENTID }}
          TWITTER_CLIENTSECRET: ${{ secrets.TWITTER_CLIENTSECRET }}
      - name: Build project
        run: make build
        env:
          TEST_SHELL: bash
          IMGUR_KEY: ${{ secrets.IMGUR_KEY }}
          OMDB_KEY: ${{ secrets.OMDB_KEY }}
          TWITTER_CLIENTID: ${{ secrets.TWITTER_CLIENTID }}
          TWITTER_CLIENTSECRET: ${{ secrets.TWITTER_CLIENTSECRET }}
